export const HERO_IMAGE = "https://cdn.poehali.dev/files/bf1d80ba-4889-42b3-b652-08820026fac2.JPG";

export const NAV_ITEMS = [
  { label: "Личное дело", href: "#about" },
  { label: "Чему научу", href: "#directions" },
  { label: "Прокачка голоса (мастер-классы и лекции)", href: "#courses" },
  { label: "Много умных слов о главном", href: "#smart" },
  { label: "Диагностика слуха", href: "#hearing" },
  { label: "Лечим музыкой", href: "#therapy" },
  { label: "В кадре", href: "#gallery" },
  { label: "Отзывы", href: "#reviews" },
];

export const BOOK = {
  title: "Сила твоего голоса",
  subtitle: "Как голос помогает лечить тело, снимать напряжение и восстанавливать энергию",
  description: "Книга о том, как звук и голос становятся инструментом исцеления. Наука, практика и личный опыт — в одном издании. Для всех, кто хочет понять связь между голосом, телом и здоровьем.",
  features: [
    "Исцеляющая сила звука",
    "Голос и тело: неразрывная связь",
    "Практики, которые работают",
    "Дыши. Говори. Пой. Будь здоров!",
  ],
  cover: "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/b967a556-ee5a-4b3a-a51c-8563f0ed9e12.png",
  formats: [
    { type: "PDF", icon: "📄", price: "500 ₽", desc: "Читай сразу после оплаты на любом устройстве" },
    { type: "EPUB", icon: "📱", price: "500 ₽", desc: "Удобный формат для читалок — iPhone, Kindle, Android" },
  ],
};

export const DIRECTIONS = [
  { icon: "🎸", title: "Рок и экстрим вокал", desc: "Гроул, скриминг, чистый звук. Техники без вреда для голоса. Приёмы: дисторшн, драйв, гуттурал, фрайскрим, шрайк, грим.", image: "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/0795aff9-50c4-45bc-b265-64d01f22b281.png" },
  { icon: "🎵", title: "Горловое пение", desc: "Тувинские, монгольские, алтайские и тибетские традиции. Уникальные обертоновые техники." },
  { icon: "🎤", title: "Эстрадный вокал", desc: "Современная эстрада, поп, джаз. Работа с образом и подачей." },
  { icon: "🔬", title: "Фонопедия", desc: "Восстановление и развитие голоса. Медицинский подход к вокалу.", image: "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/32ffd57b-11cc-436d-b5a5-bfc225179cb8.png" },
  { icon: "🧠", title: "Музыкальная психотерапия", desc: "Исцеление через звук. Авторские методики снятия блоков.", images: [
    "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/de0644bd-4748-4d63-a3ec-9e2572fd46ae.png",
    "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/0d344bec-c8c0-4e24-911f-5920aeabf4e1.png",
  ] },
  { icon: "✍️", title: "Сонграйтинг", desc: "Написание песен. От мелодии к тексту, от идеи к треку.", images: [
    "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/b4268bd7-cfa2-453d-a4b9-b447ea727546.png",
    "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/46d36d02-8dc5-429d-9a15-e1f167623613.png",
    "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/c1bef04b-1ce5-4c8d-993b-e6305c9a183f.png",
  ] },
];

export const COURSES = [
  {
    level: "Экспресс видео-курс",
    title: "Медведь на ухо",
    desc: "Фальшь — не приговор! Курс по улучшению интонирования и попадания в ноты. Самодиагностика слуха, тренировка мозга и рабочие упражнения. 21 день — и ты другой!",
    duration: "21 день",
    price: "1 000 ₽",
    tag: "Видео-курс",
    link: "/course/bear-ear",
    cover: "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/0d534d16-7a07-4977-a138-65a0a1934a91.png",
  },
  {
    level: "Онлайн-курс",
    title: "Фонический резонанс",
    desc: "Авторский курс по управлению резонаторами голоса. PDF-методичка и аудио-дорожки для самостоятельной практики — доступ навсегда после оплаты.",
    duration: "Навсегда",
    price: "1 000 ₽",
    tag: "Курс",
    link: "/course/phonic-resonance",
    cover: "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/925eee55-630b-4abd-b9e6-97fbf885573c.png",
  },
  {
    level: "Мини-курс",
    title: "База вокала для караоке",
    desc: "Опора и дыхание, резонаторы и интонация, сценический аппарат — 3 базовых навыка, которые педагоги вокала ставят в первую очередь. Для тех, кто хочет петь уверенно без педагога.",
    duration: "Навсегда",
    price: "700 ₽",
    tag: "Мини-курс",
    link: "/course/karaoke-base",
    cover: "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/d7ff4c41-f89b-4ad0-af27-bb95a2fd677f.png",
    taglines: [
      "Для тех, кто не готов заниматься с педагогом, но хочет понимать, что происходит с его голосом.",
      "Для тех, кто хочет петь в караоке уверенно, но не планирует брать регулярные уроки вокала.",
      "Если вам не нужен большой вокальный курс, а нужен понятный фундамент — этот мини-курс для вас.",
      "Не хотите становиться вокалистом. Хотите перестать мучиться в караоке.",
      "Не каждый человек хочет заниматься вокалом. Но почти каждый хочет не страдать у микрофона.",
    ],
  },
  {
    level: "Авторский курс",
    title: "Харизма 2.0",
    desc: "Курс по развитию личного влияния и коммуникативного присутствия. Нейробиология, голос, невербалика, управление вниманием — харизма как навык, поддающийся тренировке.",
    duration: "Навсегда",
    price: "1 400 ₽",
    tag: "Курс",
    link: "/course/charisma",
    cover: "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/41548357-b290-4329-8fe7-cd1c48aaed5e.png",
  },
  {
    level: "Книга",
    title: "Сила твоего голоса",
    desc: "Как голос помогает лечить тело, снимать напряжение и восстанавливать энергию. Наука, практика и личный опыт в одном издании.",
    duration: "PDF / Аудио / Бумага",
    price: "500 ₽",
    tag: "Книга",
    link: "/book",
    cover: "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/b967a556-ee5a-4b3a-a51c-8563f0ed9e12.png",
  },
];

export const VIDEOS = [
  { category: "Поёт тренер", title: "Анна Артман — живое выступление", duration: "", views: "", locked: false, youtubeId: "djxE8DmsQNw" },
  { category: "Поёт тренер", title: "Анна Артман — живое выступление 2", duration: "", views: "", locked: false, youtubeId: "fcV33kfYtzk" },
  { category: "Поёт тренер", title: "Анна Артман — живое выступление 3", duration: "", views: "", locked: false, youtubeId: "4ZnCH6Tnus8" },
  { category: "Поёт тренер", title: "Анна Артман — живое выступление 4", duration: "", views: "", locked: false, youtubeId: "BOnOTYEiASY" },
  { category: "Поёт тренер", title: "Анна Артман — живое выступление 5", duration: "", views: "", locked: false, youtubeId: "GzJ3_kLw1-c" },
  { category: "Поёт тренер", title: "Анна Артман — живое выступление 6", duration: "", views: "", locked: false, youtubeId: "BOG0U5Jr5BU" },
  { category: "Поёт тренер", title: "Анна Артман — живое выступление 7", duration: "", views: "", locked: false, youtubeId: "_oht86Q5hGQ" },
  { category: "Поёт тренер", title: "Анна Артман — живое выступление 8", duration: "", views: "", locked: false, youtubeId: "MiBtVotpcak" },
  { category: "Поёт тренер", title: "Анна Артман — живое выступление 9", duration: "", views: "", locked: false, youtubeId: "nPIwJir9Nsw" },
  { category: "Поёт тренер", title: "Анна Артман — живое выступление 10", duration: "", views: "", locked: false, youtubeId: "RRgKrasvMWE" },
  { category: "Поёт тренер", title: "Анна Артман — живое выступление 11", duration: "", views: "", locked: false, youtubeId: "hzREhhTNG94" },
  { category: "Поёт тренер", title: "Анна Артман — живое выступление 12", duration: "", views: "", locked: false, youtubeId: "muDYZ0PxtZM" },
  { category: "Поёт тренер", title: "Анна Артман — живое выступление 13", duration: "", views: "", locked: false, youtubeId: "Lb04KB3LaY8" },

];

export const GALLERY = [
  { src: "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/files/663a6c29-9aba-4259-a4d1-73d44777b797.jpg", alt: "Сцена — микрофон, синтезатор, прожекторы" },
  { src: "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/19df2869-15df-4bcd-8517-40c66edc740d.png", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/b29ca24e-d7f1-4596-b268-f20749b4aea9.jpg", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/e4d95bd6-d088-4474-9640-c82ecf77e13a.jpg", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/819f2a44-667d-45aa-a43a-1995be147b24.jpg", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/0120b599-6bd9-4ce8-8ece-97dba7a56aba.jpg", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/0db38af6-49fc-43df-a821-484ecab8f156.JPG", alt: "Анна Артман — Театр Рока" },
  { src: "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/37875366-5357-467d-8608-88ccaf3906ed.JPG", alt: "Анна Артман с микрофоном" },
  { src: "https://cdn.poehali.dev/files/c38a1712-9403-43c4-8a0e-966cc0f8287a.JPG", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/3c9a55bc-055d-4ab3-8502-7e91330a6a35.JPG", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/01728cc0-c38f-420e-94e9-4fb3c96d3e4f.jpg", alt: "Анна Артман с гитарой" },
  { src: "https://cdn.poehali.dev/files/83be4928-ff0d-4878-aa20-ddda6a063042.jpg", alt: "Анна Артман с гитарой" },
  { src: "https://cdn.poehali.dev/files/6f59419d-f1d9-4a54-aa7f-8c2dfebf8a8d.jpg", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/projects/2c2649a4-f97e-4608-8ac1-4bd4de8bd9d6/bucket/3b79e183-a330-4490-9c30-a30feb7b2eed.jpg", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/3161fc50-0f58-45d1-88cc-068bf777f777.jpg", alt: "Анна Артман с цветами" },
  { src: "https://cdn.poehali.dev/files/cefbd63f-cbde-49e1-957b-58747cdf2bc6.jpg", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/c0b26a66-7262-47ab-bbae-846b0890a800.JPG", alt: "Анна Артман — образ" },
  { src: "https://cdn.poehali.dev/files/8251277f-349a-4a84-a846-f936a16ca4ec.jpg", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/9d7cd3fe-0e22-4942-a755-dcae0f7a0cd6.JPG", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/882a1878-d018-4f8a-ab38-2eb5896a09a1.JPG", alt: "Анна Артман за синтезатором" },
  { src: "https://cdn.poehali.dev/files/7b2c95d1-3f70-41a6-815b-6317608cfaff.jpg", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/5ad2a046-b719-4034-84e4-4e36cc2394f1.JPG", alt: "Анна Артман — рок знак" },
  { src: "https://cdn.poehali.dev/files/5ddf804d-75ca-4694-8ef5-0eadee8acbe2.JPG", alt: "Анна Артман за кулисами" },
  { src: "https://cdn.poehali.dev/files/f290bce3-4e99-4af9-ae5c-d1b83c50b0d1.JPG", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/e6c7a074-ee2b-4c3d-8dd6-03f7a28b5620.JPG", alt: "Анна Артман с красной гитарой" },
  { src: "https://cdn.poehali.dev/files/1bd8aa17-6807-4209-8b0d-9201c0f9e573.JPG", alt: "Анна Артман с электрогитарой" },
  { src: "https://cdn.poehali.dev/files/f26453b3-5c39-45cd-963b-798610959526.JPG", alt: "Анна Артман с гитарой" },
  { src: "https://cdn.poehali.dev/files/57db4e99-df19-4bf3-bb92-ec7cb268f1e7.JPG", alt: "Анна Артман — тёмный образ" },
  { src: "https://cdn.poehali.dev/files/e75c8fab-4151-4834-bc5f-84e7c3432154.JPG", alt: "Анна Артман в очках" },
  { src: "https://cdn.poehali.dev/files/86e4b4b7-5834-420b-a509-fa9b88fb90de.jpg", alt: "Анна Артман с микрофоном в красном образе" },
  { src: "https://cdn.poehali.dev/files/42610e31-25db-4e0b-9d12-63f5359bc087.jpg", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/3b4958a2-47be-4da6-9642-b482eff20d37.jpg", alt: "Анна Артман — панк образ" },
  { src: "https://cdn.poehali.dev/files/8c769c03-2dbc-47d3-8235-44ff7d9f62f6.jpg", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/8a833a4e-e151-42b7-aad1-c5b8c6983adc.jpg", alt: "Анна Артман" },
  { src: "https://cdn.poehali.dev/files/fabf4e0b-b2e4-4a70-8b57-b6315c29ecaf.jpg", alt: "Анна Артман в синем свете" },
  { src: "https://cdn.poehali.dev/files/d214aa7f-dab0-4a0f-8bf4-46648ca9251c.jpg", alt: "Анна Артман — образ демона" },
  { src: "https://cdn.poehali.dev/files/a6138ed6-1959-4a1d-96ff-dce2f805d89e.jpg", alt: "Анна Артман с микрофоном" },
  { src: "https://cdn.poehali.dev/files/7fdea77b-2384-4a66-a65d-4682a387ca87.jpg", alt: "Анна Артман — портрет" },
  { src: "https://cdn.poehali.dev/files/0194d75e-1f36-4716-a118-a81386dff651.jpg", alt: "Анна Артман" },
];

export const ARTICLES = [
  {
    tag: "Техника",
    title: "И снова про опору",
    excerpt: "«Пой на опоре» — слышали все. Понял хоть кто-нибудь? Разбираем, что это за зверь, почему он важен и как его наконец найти — без эзотерики и лишних слов.",
    readTime: "7 мин",
    emoji: "🏋️",
  },
  {
    tag: "Техника",
    title: "Пение в маску",
    excerpt: "Нет, маска здесь не медицинская. Это резонаторы — и именно они делают голос объёмным, ярким и неутомляемым. Как это работает и зачем вам это знать.",
    readTime: "6 мин",
    emoji: "🎭",
  },
  {
    tag: "Здоровье",
    title: "Голос «занемог»",
    excerpt: "Охрип, пропал, сел — и что теперь? Разбираем причины, первую помощь голосу и главное правило: когда петь нельзя даже чуть-чуть.",
    readTime: "5 мин",
    emoji: "🤒",
  },
  {
    tag: "Психология",
    title: "Как подружиться с песней",
    excerpt: "Выучил слова, знаешь ноты, а песня всё равно «не идёт». Это не про технику — это про отношения. Как выстроить контакт с материалом и перестать бояться сцены.",
    readTime: "8 мин",
    emoji: "🤝",
  },
  {
    tag: "Биология",
    title: "Играй, гормон!",
    excerpt: "Голос — это не только мышцы. Гормоны управляют им ежедневно: стресс, усталость, цикл, возраст. Разбираемся, как тело влияет на звук и что с этим делать.",
    readTime: "9 мин",
    emoji: "🧬",
  },
  {
    tag: "Разоблачение",
    title: "Вокальные мифы",
    excerpt: "«Слух не развить», «холодное нельзя», «если нет голоса — нет смысла». Разбираем 10 мифов, которые мешают петь миллионам людей — и говорим правду.",
    readTime: "10 мин",
    emoji: "💥",
  },
  {
    tag: "Практика",
    title: "Дыхание как фундамент",
    excerpt: "Большинство вокальных проблем начинается здесь — в неправильном дыхании. Не в горле, не в голосовых связках. Объясняем физиологию и даём рабочие упражнения.",
    readTime: "7 мин",
    emoji: "🌬️",
  },
  {
    tag: "Психология",
    title: "Страх сцены: инструкция по применению",
    excerpt: "Тремор, забытые слова, ватные ноги. Это не слабость — это физиология. Рассказываем, почему тело так реагирует и как превратить страх в топливо для выступления.",
    readTime: "8 мин",
    emoji: "🎤",
  },
  {
    tag: "Здоровье",
    title: "Вокал и возраст: голос меняется",
    excerpt: "Голос — живой инструмент. Он меняется с возрастом, и это нормально. Как работать с голосом в 20, 40 и 60 — и почему опытные певцы часто звучат лучше молодых.",
    readTime: "6 мин",
    emoji: "⏳",
  },
  {
    tag: "Практика",
    title: "Зачем петь тому, кто «не умеет»",
    excerpt: "Пение — это не привилегия тех, кому «дано». Это базовая потребность человека, встроенная эволюцией. О терапевтическом, социальном и просто человеческом смысле голоса.",
    readTime: "5 мин",
    emoji: "🌱",
  },
  {
    tag: "Разоблачение",
    title: "Про того самого медведя",
    excerpt: "«Медведь на ухо наступил» — самая популярная отмазка от пения. Разбираемся, существует ли он вообще, что на самом деле стоит за этой фразой и почему почти любой человек способен петь.",
    readTime: "6 мин",
    emoji: "🐻",
  },
];

export const REVIEWS = [
  {
    name: "Мария К.",
    role: "Рок-вокалистка",
    text: "Анна — единственный педагог, которая объяснила мне, как делать экстрим без боли. За 4 месяца я не только сохранила голос, но и вышла на новый уровень.",
    stars: 5,
  },
  {
    name: "Дмитрий В.",
    role: "Начинающий музыкант",
    text: "Пришёл с нуля и боялся даже петь в душе. Методика «Чем он это сделал» — это откровение. Теперь пою в группе.",
    stars: 5,
  },
  {
    name: "Алиса Т.",
    role: "Психолог",
    text: "Прошла курс музыкотерапии. Удивительно, как звук работает с телом. Анна создала безопасное пространство для исследования голоса.",
    stars: 5,
  },
  {
    name: "Кирилл М.",
    role: "Вокалист группы «Север»",
    text: "Три года искал педагога по горловому пению. Нашёл в Театре Рока. Результат превзошёл ожидания.",
    stars: 5,
  },
];